name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
          - os: windows-latest
          # - os: macos-latest

    runs-on: ${{ matrix.platform.os }}

    steps:
    - uses: actions/checkout@v4
    # - name: configure
    #   run: ./configure
    - name: make
      run: make
    # - name: make check
    #   run: make check
    # - name: make distcheck
    #   run: make distcheck
